### ISSUE TITLE
City Name problem

### ISSUE THREAD

**Issue by fpicard102** [JoomShaper/SP-Weather#10]
Hi, 

I have update my SP-weather module on a Joomla 3.5 website, but my location doesn't work. I want to use the city LANDRES, FRANCE (WOEID: 601178). If a use this city on the module, this one leave blank. 
If I use Paris for example All is OK and if I use REIMS Humidity and Temp is OK but no forecast. Can you help me? Regards

**Comment by rifatwahid** [comment]
Hi,
We have updated this issue again in v 2.2.5. Please update your sp weather module from: https://www.joomshaper.com/downloads/extension/sp-weather

- Thanks

**Comment by fpicard102** [comment]
Hi,


It works Great. Thanks for your reactivity.


Regards


________________________________
De : Rifat wahid ALIF <notifications@github.com>
Envoyé : vendredi 15 avril 2016 11:28
À : JoomShaper/SP-Weather
Cc : fpicard102
Objet : Re: [JoomShaper/SP-Weather] City Name problem (#10)


Hi,
We have updated this issue again in v 2.2.5. Please update your sp weather module from: https://www.joomshaper.com/downloads/extension/sp-weather

SP Weather | Download - JoomShaper<https://www.joomshaper.com/downloads/extension/sp-weather>
www.joomshaper.com
SP Weather is a free Weather module for joomla



  *   Thanks

-
