### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by leficek** [JoomShaper/SP-Weather#13]
Hello
Sp-Weather not Working today. even your demo is too. 
Cannot get Esfahan, Iran location id in module mod_sp_weather. Please also make sure that you have inserted city name.

**Comment by wezetel** [comment]
Same here. Probably Yahoo changed something?

**Comment by NexonSU** [comment]
From www.joomshaper.com:
Important EOL Notice: Since Jan. 3, 2019, the weather.yahooapis.com for Yahoo Weather API was retired. The module will not work until the next update. We have to change weather resource.

**Comment by rifatwahid** [comment]
Hi,
We have released a new version on may with 5 new API platform which including yahoo API also: https://www.joomshaper.com/joomla-extensions/sp-weather

- Thanks
